#!/usr/bin/env node

function log(host, message){
    console.log(`[${host}] ${message}`)
}
function execute(command,host){
    //return new Promise((resolve,reject)=>{
        log(host,"running "+command);
        const exec = require('child_process').exec;
        const ls = exec(command);
        ls.stdout.on('data', function (data) {
            const output = data.toString().replace("\n","").replace("\r","");
            if(output !== ""){
                log(host,output);
            }
          });
          
          ls.stderr.on('data', function (data) {
            const output = data.toString().replace("\n","").replace("\r","");
            if(output !== ""){
                log(host,output);
            }
          });
          
          ls.on('exit', function (code) {
            if(code.toString() === "0"){
                //resolve();
            }else{
                //throw new Error("exited with code "+code);
            }
          });
    //});
} 

async function main(args){
    const users = ["james@192.168.1.64","pi@192.168.1.82","james@192.168.1.63","pi@light","james@192.168.1.57","pi@192.168.1.18","james@192.168.1.18","pi@pihole"];
    const command = "\""+args[2]+"\"";
    let user;
    for(let i=0;i<users.length;i++){
        user = users[i];
        try{
            execute(`ssh -oStrictHostKeyChecking=no ${user} ${command}`,users[i]);
        }
        catch(e){
            console.log(e);
        }
        user = undefined;
    };
}
main(process.argv);
