#!/usr/bin/env node
function execute(command){
    return new Promise((resolve,reject)=>{
        console.log("running "+command);
        const exec = require('child_process').exec;
        const ls = exec(command);
        ls.stdout.on('data', function (data) {
            const output = data.toString().replace("\n","").replace("\r","");
            if(output !== ""){
                console.log(output);
            }
          });
          
          ls.stderr.on('data', function (data) {
            const output = data.toString().replace("\n","").replace("\r","");
            if(output !== ""){
                console.log(output);
            }
          });
          
          ls.on('exit', function (code) {
            if(code.toString() === "0"){
                resolve();
            }else{
                reject("exited with code "+code);
            }
          });
    });
} 

async function main(args){
    const users = ["user@server1","user@server2"];
    const command = "\""+args[2]+"\"";
    let user;
    for(let i=0;i<users.length;i++){
        user = users[i];
        try{
            await execute(`ssh -oStrictHostKeyChecking=no ${user} ${command}`);
        }
        catch(e){
            console.log(e);
        }
        user = undefined;
    };
}
main(process.argv);